spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.109/sell_system?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell



wechat:
  mpAppId: wxd898fcb01713c658
#  mpAppId: wx708930db084132a2
  mpAppSecret: 54da4c8e2a0d8de6e64f0ddbdc59b76e
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: G:/h5.p12
  notifyUrl: http://sigur.s1.natapp.cc/sell/pay/notify